import os

import openai

from .base import Model


class OpenAIModel(Model):
    """OpenAI model that can be run on prompts.

    Args:
        api_key: API key to use to access the model.
        model: Model to use.
        temperature: The value used to module the next token probabilities.
        top_p: The cumulative probability for top-p filtering.
        max_tokens: The maximum number of tokens to generate.
    """

    def __init__(
        self,
        model: str = "text-davinci-003",
        temperature: float = 0,
        top_p: float = 1,
        max_tokens: int = 1024,
    ):
        self.model = model
        self.temperature = temperature
        self.top_p = top_p
        self.max_tokens = max_tokens

        openai.api_key = os.environ["OPENAI_API_KEY"]

    def run(self, prompt: str) -> str:
        """
        Run the model on `prompt`.

        Args:
            prompt: Prompt to give the model.

        Returns:
            The result generated by the model.
        """
        response = openai.Completion.create(
            engine=self.model,
            prompt=prompt,
            temperature=self.temperature,
            top_p=self.top_p,
            max_tokens=self.max_tokens,
        )
        return response.choices[0].text
