# This workflow triggers checks with pre-commit.

name: Test

on: [push]

jobs:
  pre-commit:
    name: pre-commit
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/pre-commit.yml
